### ISSUE TITLE
[Site]: navigator break website build

### ISSUE THREAD

**Issue by chaokunyang** [apache/fury-site#201]
### Current State

**Description of the current state**:
```
Error: Unable to build website for locale en-US.

    at tryToBuildLocale (/home/runner/work/fury-site/fury-site/node_modules/@docusaurus/core/lib/commands/build.js:55:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:[95](https://github.com/apache/fury-site/actions/runs/11763536374/job/32767638098#step:6:96):5)
    at async mapAsyncSequential (/home/runner/work/fury-site/fury-site/node_modules/@docusaurus/utils/lib/jsUtils.js:44:24)
    at async Command.build (/home/runner/work/fury-site/fury-site/node_modules/@docusaurus/core/lib/commands/build.js:82:21) {
  [cause]: Error: Failed to compile due to Webpack errors.
  Error: Docusaurus server-side rendering could not render static page with path /home/ because of error: navigator is not defined
  It looks like you are using code that should run on the client-side only.
  To get around it, try using `<BrowserOnly>` (https://docusaurus.io/docs/docusaurus-core/#browseronly) or `ExecutionEnvironment` (https://docusaurus.io/docs/docusaurus-core/#executionenvironment).
  It might also require to wrap your client code in `useEffect` hook and/or import a third-party library dynamically (if any).
  
  --------------------------
  
  Error: Docusaurus server-side rendering could not render static page with path /home/components/HomePageLanguageCard because of error: navigator is not defined
  It looks like you are using code that should run on the client-side only.
  To get around it, try using `<BrowserOnly>` (https://docusaurus.io/docs/docusaurus-core/#browseronly) or `ExecutionEnvironment` (https://docusaurus.io/docs/docusaurus-core/#executionenvironment).
  It might also require to wrap your client code in `useEffect` hook and/or import a third-party library dynamically (if any).
  
  --------------------------
  
  Error: Docusaurus server-side rendering could not render static page with path / because of error: navigator is not defined
  It looks like you are using code that should run on the client-side only.
  To get around it, try using `<BrowserOnly>` (https://docusaurus.io/docs/docusaurus-core/#browseronly) or `ExecutionEnvironment` (https://docusaurus.io/docs/docusaurus-core/#executionenvironment).
  It might also require to wrap your client code in `useEffect` hook and/or import a third-party library dynamically (if any).
      at /home/runner/work/fury-site/fury-site/node_modules/@docusaurus/core/lib/webpack/utils.js:207:24
      at /home/runner/work/fury-site/fury-site/node_modules/webpack/lib/MultiCompiler.js:554:14
      at processQueueWorker (/home/runner/work/fury-site/fury-site/node_modules/webpack/lib/MultiCompiler.js:491:6)
      at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
}
```

**Link to the wensite page, allow developers to better understand the problem**:

https://github.com/apache/fury-site/actions/runs/11763536374/job/32767638098

**Screenshots (if relevant)**:
![image](https://github.com/user-attachments/assets/18842320-0345-46d4-b2a6-37febbdbba16)

### Desired State

**Description of the change you are proposing**:

### Would you like to fix this issue?

None

**Comment by chaokunyang** [comment]
Seems introduced in https://github.com/apache/fury-site/pull/198

**Comment by LofiSu** [comment]
Has it been resolved now? If not, I’ll take care of it.

**Comment by chaokunyang** [comment]
Yes, it's fixed laready. let me close this issue
